# Generated by Django 2.2.6 on 2019-11-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs', '0001_initial'),
        ('branches', '0002_auto_20191105_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='limbs',
            field=models.ManyToManyField(to='limbs.Limb'),
        ),
    ]
