# Generated by Django 2.2.6 on 2019-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_limbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='limbs',
        ),
    ]
