# Generated by Django 2.2.6 on 2019-11-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_remove_branch_limbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='title',
            field=models.CharField(default='Untitled Branch', max_length=255),
        ),
    ]
