# Generated by Django 2.2.6 on 2019-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='playlist_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
