# Generated by Django 2.2.6 on 2019-10-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(default=0),
        ),
    ]
