# Generated by Django 2.2.6 on 2019-11-05 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_url', models.CharField(max_length=255)),
                ('artist_id', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('event_city', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_id', models.IntegerField()),
                ('venue_url', models.CharField(max_length=255)),
                ('song_url', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('song_preview_url', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
