# Generated by Django 2.2.6 on 2019-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limb',
            name='use_currently_playing',
            field=models.BooleanField(default=True),
        ),
    ]
