# Generated by Django 2.2.6 on 2019-11-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_remove_branch_limbs'),
        ('limbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limb',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.Branch'),
        ),
    ]
