# Generated by Django 2.2.6 on 2019-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbs', '0002_limb_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='limb',
            name='event_uri',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
