# Generated by Django 2.2.6 on 2019-10-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('songs', '0002_song_duration_ms'),
        ('limbs', '0002_limb_use_currently_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='limb',
            name='event_list',
            field=models.ManyToManyField(to='events.Event'),
        ),
        migrations.AddField(
            model_name='limb',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='limb',
            name='song_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
        ),
    ]
